// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Politio.Api.Data;

#nullable disable

namespace Politio.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230511041624_InitialPlayersCreate")]
    partial class InitialPlayersCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Politio.Api.Data.MyString", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId1")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId2")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId1");

                    b.HasIndex("PlayerId2");

                    b.ToTable("MyString");
                });

            modelBuilder.Entity("Politio.Api.Data.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Activation")
                        .HasColumnType("int");

                    b.Property<string>("ActualStanding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Authoritarian")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoinsTotal")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GamesTotal")
                        .HasColumnType("int");

                    b.Property<int>("GudosTotal")
                        .HasColumnType("int");

                    b.Property<int>("KudosOverall")
                        .HasColumnType("int");

                    b.Property<int>("Left")
                        .HasColumnType("int");

                    b.Property<int>("Libertarian")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Right")
                        .HasColumnType("int");

                    b.Property<int>("Strikes")
                        .HasColumnType("int");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Politio.Api.Data.MyString", b =>
                {
                    b.HasOne("Politio.Api.Data.Player", null)
                        .WithMany("UnlockedAvatars")
                        .HasForeignKey("PlayerId");

                    b.HasOne("Politio.Api.Data.Player", null)
                        .WithMany("UnlockedTitleFirstWords")
                        .HasForeignKey("PlayerId1");

                    b.HasOne("Politio.Api.Data.Player", null)
                        .WithMany("UnlockedTitleSecondWords")
                        .HasForeignKey("PlayerId2");
                });

            modelBuilder.Entity("Politio.Api.Data.Player", b =>
                {
                    b.Navigation("UnlockedAvatars");

                    b.Navigation("UnlockedTitleFirstWords");

                    b.Navigation("UnlockedTitleSecondWords");
                });
#pragma warning restore 612, 618
        }
    }
}
