name: PolitickGame 2023 Front-End CI/CD

on:
  workflow_dispatch:
  push:
    paths: 
      - Politick/**
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Packages
        run: npm ci
        working-directory: ./Politick
      - name: Lint Code
        working-directory: ./Politick
        run: npm run lint
      - name: Prettier Check
        working-directory: ./Politick
        run: npm run format:check
      - name: Build Vue App 
        working-directory: ./Politick
        run: npm run build
      - name: Run Vitest Unit Tests
        run: npm run test:unit
        working-directory: ./Politick
     
      - name: Install ncftp
        run: sudo apt-get install ncftp

      - name: Upload dist folder to Azure Web App
        run: |
          ncftpput -R -v -u $FTPS_USERNAME -p $FTPS_PASSWORD $FTPS_HOST /site/wwwroot/dist ./Politick/dist
        env:
          FTP_USERNAME: ${{ secrets.FTPS_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTPS_PASSWORD }}
          FTP_HOST: ${{ secrets.FTPS_HOST }}
