name: PolitickGame 2023 Front-End CI/CD

on:
  workflow_dispatch:
  push:
    paths: 
      - Politick/**
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Packages
        run: npm ci
        working-directory: ./Politick
      - name: Lint Code
        working-directory: ./Politick
        run: npm run lint
      - name: Prettier Check
        working-directory: ./Politick
        run: npm run format:check
      - name: Build Vue App 
        working-directory: ./Politick
        run: npm run build
      - name: Run Vitest Unit Tests
        run: npm run test:unit
        working-directory: ./Politick
     
      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: PolitickGame
          slot-name: 'Production' # Optional
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_API }}
          package: /site/wwwroot/dist
